### ISSUE TITLE
TELEMAT json file problem

### ISSUE THREAD

**Issue by 16D** [Barracuda09/PyPSADiag#8]
I can't open json file for TELEMAT:
![image](https://github.com/user-attachments/assets/60f425d0-3e3c-4bc8-b57e-71b2cfbc70dc)

**Comment by Barracuda09** [comment]
Thanks for reporting. 
Should be fixed with new commit [d78403d](https://github.com/Barracuda09/PyPSADiag/commit/d78403d654c4f103442759c5f8e58e5f0f2fe471)

**Comment by Barracuda09** [comment]
Fixed
